#!/bin/bash

# temp (v2.0)
# 2024.09.06, by @zachleach

YEAR='2024' BASE='2023-12-30'
for w in {0..365..7}; do
	sunday="$(date -d "${BASE} +${w} days" '+%Y-%m-%d')"
	echo ${sunday} >> ${YEAR}.md
	echo ${sunday} \* && touch ${sunday}.md
	for d in {1..6}; do
		day=$(date -d "${sunday} +${d} days" '+%Y-%m-%d')
		echo ${day} >> ${sunday}.md
		echo ${day} && touch ${day}.md
	done
done
